### Legacy EFF API - League Data Tests

### 1. Leagues.php - ReadList by UserID
POST {{baseUrl}}/eff/eff_api/Leagues.php?f=ReadList
Content-Type: application/x-www-form-urlencoded

_format=json&_type=byUserID&userID={{testUserID}}

### 2. Divisions.php - ReadList by LeagueID
POST {{baseUrl}}/eff/eff_api/Divisions.php?f=ReadList
Content-Type: application/x-www-form-urlencoded

_format=json&_type=byLeagueID&leagueID={{testLeagueID}}

### 3. Teams.php - ReadList by DivisionID
POST {{baseUrl}}/eff/eff_api/Teams.php?f=ReadList
Content-Type: application/x-www-form-urlencoded

_format=json&_type=byDivisionID&divisionID={{testDivisionID}}

### 4. Teams.php - ReadList by LeagueID
POST {{baseUrl}}/eff/eff_api/Teams.php?f=ReadList
Content-Type: application/x-www-form-urlencoded

_format=json&_type=byLeagueID&leagueID={{testLeagueID}}

### 5. DivisionNotes.php - ReadList by DivisionID
POST {{baseUrl}}/eff/eff_api/DivisionNotes.php?f=ReadList
Content-Type: application/x-www-form-urlencoded

_format=json&_type=byDivisionID&divisionID={{testDivisionID}}

### 6. Teams.php - ReadList with specific teamID
POST {{baseUrl}}/eff/eff_api/Teams.php?f=ReadList
Content-Type: application/x-www-form-urlencoded

_format=json&_type=byTeamID&teamID={{testTeamID}}
