@base-url = https://eff-api-150703383580.us-central1.run.app
@user-agent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36
@format = json
@user-name = nigel@bowmantx.com
@user-pass = PASSWORD_9
@user-id = 9
@real-competition-id = 21
@real-competition-match-day = 38
@league-id = 63
@division-id = 130
@team-id = 1187
@match-team-id = 16971


### 01. SignIn
# @name login

POST {{base-url}}/eff/eff_api/SignIn.php HTTP/1.1
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
User-Agent: {{user-agent}}

_format={{format}}
&userEmail={{user-name}}
&userPassword={{user-pass}}


### --> Get the token
@access-token = {{login.response.body.values.token}}


### 02. Matches - ReadList - byLeagueID = {{league-id}}

POST {{base-url}}/eff/eff_api/Matches.php?f=ReadList
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
User-Agent: {{user-agent}}
Authorization: Bearer {{access-token}}

_format={{format}}
&_type=byLeagueID
&leagueID={{league-id}}


### 03. Matches - ReadList - byDivisionID = {{division-id}}

POST {{base-url}}/eff/eff_api/Matches.php?f=ReadList
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
User-Agent: {{user-agent}}
Authorization: Bearer {{access-token}}

_format={{format}}
&_type=byDivisionID
&divisionID={{division-id}}
