@base-url = https://eff-api-150703383580.us-central1.run.app
@user-name = nigel@bowmantx.com
@user-pass = PASSWORD_9
@format = json
@league-id = 63
@division-id = 130
@team-id = 1187


### SignIn (Token)
# @name signin

POST {{base-url}}/eff/eff_api/Users.php?f=SignIn
Content-Type: application/x-www-form-urlencoded

_format={{format}}
&userEmail={{user-name}}
&userPassword={{user-pass}}


### Extract token
@access-token = {{signin.response.body.items[0].values.token}}


### Legacy Leagues ReadList

POST {{base-url}}/eff/eff_api/Leagues.php?f=ReadList
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{access-token}}

_format={{format}}
&_type=byUserID
&userID=9


### Legacy Divisions ReadList

POST {{base-url}}/eff/eff_api/Divisions.php?f=ReadList
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{access-token}}

_format={{format}}
&_type=byLeagueID
&leagueID={{league-id}}


### Legacy Teams ReadList

POST {{base-url}}/eff/eff_api/Teams.php?f=ReadList
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{access-token}}

_format={{format}}
&_type=byDivisionID
&divisionID={{division-id}}


### Legacy Team Member Transfers ReadList

POST {{base-url}}/eff/eff_api/TeamMemberTransfers.php?f=ReadList
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{access-token}}

_format={{format}}
&teamID={{team-id}}
