@base-url = https://eff-api-150703383580.us-central1.run.app
@user-name = nigel@bowmantx.com
@user-pass = PASSWORD_9
@format = json
@division-id = 130
@real-competition-id = 21
@match-id = 1


### SignIn (Token)
# @name signin

POST {{base-url}}/eff/eff_api/Users.php?f=SignIn
Content-Type: application/x-www-form-urlencoded

_format={{format}}
&userEmail={{user-name}}
&userPassword={{user-pass}}


### Extract token
@access-token = {{signin.response.body.items[0].values.token}}


### Legacy Matches ReadList

POST {{base-url}}/eff/eff_api/Matches.php?f=ReadList
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{access-token}}

_format={{format}}
&divisionID={{division-id}}


### Legacy Match Teams ReadList

POST {{base-url}}/eff/eff_api/MatchTeams.php?f=ReadList
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{access-token}}

_format={{format}}
&matchID={{match-id}}


### Legacy Real Matches ReadList

POST {{base-url}}/eff/eff_api/RealMatches.php?f=ReadList
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{access-token}}

_format={{format}}
&realCompetitionID={{real-competition-id}}
&realCompetitionSeasonID=2025


### Legacy Real Match Teams ReadList

POST {{base-url}}/eff/eff_api/RealMatchTeams.php?f=ReadList
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{access-token}}

_format={{format}}
&realMatchID=1
