@base-url = https://eff-api-150703383580.us-central1.run.app
@format = json


### TopEPL
# Fetch top EPL data (public endpoint, no auth required)

POST {{base-url}}/eff/eff_api/TopEPL.php
Content-Type: application/x-www-form-urlencoded

_format={{format}}
