@base-url = https://eff-api-150703383580.us-central1.run.app
@user-name = nigel@bowmantx.com
@user-pass = PASSWORD_9
@league-id = 63
@division-id = 130
@team-id = 1187


### SignIn (Token)
# @name signin

POST {{base-url}}/api/auth/signin
Content-Type: application/json

{
  "userEmail": "{{user-name}}",
  "userPassword": "{{user-pass}}"
}


### Extract token
@access-token = {{signin.response.body.token}}


### Leagues ReadList

POST {{base-url}}/api/leagues/readlist
Content-Type: application/json
Authorization: Bearer {{access-token}}

{
  "userID": 9
}


### Divisions ReadList

POST {{base-url}}/api/divisions/readlist
Content-Type: application/json
Authorization: Bearer {{access-token}}

{
  "leagueID": {{league-id}}
}


### Division Notes ReadList

POST {{base-url}}/api/divisionnotes/readlist
Content-Type: application/json
Authorization: Bearer {{access-token}}

{
  "divisionID": {{division-id}}
}


### Teams ReadList

POST {{base-url}}/api/teams/readlist
Content-Type: application/json
Authorization: Bearer {{access-token}}

{
  "divisionID": {{division-id}}
}


### Team Member Transfers ReadList

POST {{base-url}}/api/teammembertransfers/readlist
Content-Type: application/json
Authorization: Bearer {{access-token}}

{
  "teamID": {{team-id}}
}
