from datetime import datetime
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy import Integer, String, Date, DateTime, TinyInteger, SmallInteger, ForeignKey, Text, Float

from app.database import Base


class User(Base):
    __tablename__ = "Users"

    userID: Mapped[int] = mapped_column(Integer, primary_key=True)
    userEmail: Mapped[str] = mapped_column(String(128), unique=True, nullable=False)
    userPassword: Mapped[str] = mapped_column(String(255), nullable=False)
    userName: Mapped[str] = mapped_column(String(128), nullable=False)
    userLevel: Mapped[int] = mapped_column(TinyInteger, nullable=False)
    firstName: Mapped[str] = mapped_column(String(50), nullable=False)
    lastName: Mapped[str] = mapped_column(String(50), nullable=False)
    birthday: Mapped[datetime] = mapped_column(Date, nullable=False)
    country: Mapped[str | None] = mapped_column(String(50))
    state: Mapped[str | None] = mapped_column(String(50))
    city: Mapped[str | None] = mapped_column(String(50))
    phoneNumber: Mapped[str | None] = mapped_column(String(15))
    timeZone: Mapped[str | None] = mapped_column(String(20))
    userAvatar: Mapped[str | None] = mapped_column(String(128))
    favoriteTeam: Mapped[str | None] = mapped_column(String(50))
    lastSignInDate: Mapped[datetime | None] = mapped_column(DateTime)
    lastSignInIP: Mapped[str | None] = mapped_column(String(15))
    createdIn: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    updatedIn: Mapped[datetime | None] = mapped_column(DateTime)


class RealCompetition(Base):
    __tablename__ = "RealCompetitions"

    realCompetitionID: Mapped[int] = mapped_column(Integer, primary_key=True)
    prevRealCompetitionID: Mapped[int | None] = mapped_column(Integer)
    nextRealCompetitionID: Mapped[int | None] = mapped_column(Integer)
    realCompetitionUID: Mapped[str] = mapped_column(String(20), nullable=False)
    realCompetitionSYMID: Mapped[str] = mapped_column(String(20), nullable=False)
    realCompetitionName: Mapped[str] = mapped_column(String(100), nullable=False)
    realCompetitionCountry: Mapped[str] = mapped_column(String(100), nullable=False)
    realCompetitionSeasonId: Mapped[str] = mapped_column(String(20), nullable=False)
    realCompetitionSeasonName: Mapped[str] = mapped_column(String(100), nullable=False)
    realCompetitionFirstMatchDay: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    realCompetitionLastMatchDay: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    realCompetitionExtraMatchDay: Mapped[int | None] = mapped_column(SmallInteger)
    useExtraRealCompetition: Mapped[bool] = mapped_column(TinyInteger, default=1)
    baseRealCompetitionID: Mapped[int | None] = mapped_column(Integer)
    extraRealCompetitionID: Mapped[int | None] = mapped_column(Integer)
    calcStandings: Mapped[bool] = mapped_column(TinyInteger, nullable=False)
    lastF7Date: Mapped[datetime] = mapped_column(DateTime, default=datetime(2000, 1, 1))
    lastF42Date: Mapped[datetime] = mapped_column(DateTime, default=datetime(2000, 1, 1))
    lastFDate: Mapped[datetime] = mapped_column(DateTime, default=datetime(2000, 1, 1))
    createdIn: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    updatedIn: Mapped[datetime | None] = mapped_column(DateTime)


class Lookup(Base):
    __tablename__ = "Lookups"

    lookupID: Mapped[int] = mapped_column(Integer, primary_key=True)
    lookupNum: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    position: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    lookupKey: Mapped[str] = mapped_column(String(20), nullable=False)
    lookupCode: Mapped[str] = mapped_column(String(10), nullable=False)
    lookupText: Mapped[str] = mapped_column(String(50), nullable=False)


class League(Base):
    __tablename__ = "Leagues"

    leagueID: Mapped[int] = mapped_column(Integer, primary_key=True)
    baseRealCompetitionID: Mapped[int] = mapped_column(Integer, nullable=False)
    extraRealCompetitionID: Mapped[int | None] = mapped_column(Integer)
    leagueName: Mapped[str] = mapped_column(String(128), nullable=False)
    leaguePassword: Mapped[str] = mapped_column(String(255), nullable=False)
    commissionerID: Mapped[int] = mapped_column(Integer, nullable=False)
    prevLeagueID: Mapped[int | None] = mapped_column(Integer)
    nextLeagueID: Mapped[int | None] = mapped_column(Integer)
    season: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    seasonNum: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    numDivisions: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    leagueType: Mapped[int] = mapped_column(TinyInteger, nullable=False)
    gameType: Mapped[int] = mapped_column(TinyInteger, nullable=False)
    scoringSystem: Mapped[int] = mapped_column(TinyInteger, nullable=False)
    tradeDeadline: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    publishLeague: Mapped[bool] = mapped_column(TinyInteger, nullable=False)
    seasonStatus: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    totalTeams: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    availableTeams: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    totPromoted: Mapped[int] = mapped_column(TinyInteger, default=2)
    maxFranchiseMembers: Mapped[int] = mapped_column(TinyInteger, default=2)
    maxWaiver: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    minEPLTeam: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    minPlayer: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    minGoalkeeper: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    minDefender: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    minMidfielder: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    minStriker: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    maxEPLTeam: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    maxPlayer: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    maxGoalkeeper: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    maxDefender: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    maxMidfielder: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    maxStriker: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    autoEPLTeam: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    autoGoalkeeper: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    autoDefender: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    autoMidfielder: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    autoStriker: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    createdBy: Mapped[int] = mapped_column(Integer, nullable=False)
    createdIn: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    updatedBy: Mapped[int | None] = mapped_column(Integer)
    updatedIn: Mapped[datetime | None] = mapped_column(DateTime)


class Division(Base):
    __tablename__ = "Divisions"

    divisionID: Mapped[int] = mapped_column(Integer, primary_key=True)
    baseRealCompetitionID: Mapped[int] = mapped_column(Integer, nullable=False)
    extraRealCompetitionID: Mapped[int | None] = mapped_column(Integer)
    matchDayMapKey: Mapped[str | None] = mapped_column(String(20))
    leagueID: Mapped[int] = mapped_column(Integer, ForeignKey("Leagues.leagueID"), nullable=False)
    commissionerID: Mapped[int] = mapped_column(Integer, nullable=False)
    prevLeagueID: Mapped[int | None] = mapped_column(Integer)
    nextLeagueID: Mapped[int | None] = mapped_column(Integer)
    prevDivisionID: Mapped[int | None] = mapped_column(Integer)
    nextDivisionID: Mapped[int | None] = mapped_column(Integer)
    season: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    seasonNum: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    leagueMatches: Mapped[int] = mapped_column(TinyInteger, default=0)
    divisionMatches: Mapped[int] = mapped_column(TinyInteger, default=0)
    draftType: Mapped[str] = mapped_column(String(1), nullable=False)
    draftDate: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    draftCompleteDate: Mapped[datetime | None] = mapped_column(DateTime)
    draftStatus: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    draftTime: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    draftingStart: Mapped[datetime | None] = mapped_column(DateTime)
    draftingFinish: Mapped[datetime | None] = mapped_column(DateTime)
    draftingLimit: Mapped[datetime | None] = mapped_column(DateTime)
    draftingRound: Mapped[int | None] = mapped_column(SmallInteger)
    draftingMemberOrder: Mapped[int | None] = mapped_column(SmallInteger)
    draftingTeamOrder: Mapped[int | None] = mapped_column(SmallInteger)
    draftingNextTeamOrder: Mapped[int | None] = mapped_column(SmallInteger)
    draftingUsers: Mapped[str] = mapped_column(Text, nullable=False)
    draftingHooks: Mapped[int] = mapped_column(SmallInteger, default=0)
    franchiseMembers: Mapped[str] = mapped_column(Text, nullable=False)
    firstRealCompetitionMatchDay: Mapped[int | None] = mapped_column(SmallInteger)
    lastRealCompetitionMatchDay: Mapped[int | None] = mapped_column(SmallInteger)
    waiverStatus: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    matchDay: Mapped[int | None] = mapped_column(SmallInteger)
    isCupMatchDay: Mapped[bool | None] = mapped_column(TinyInteger)
    isDivisionCupMatchDay: Mapped[bool | None] = mapped_column(TinyInteger)
    totalTeams: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    numTeams: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    availableTeams: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    divisionType: Mapped[str] = mapped_column(String(1), nullable=False)
    createdBy: Mapped[int] = mapped_column(Integer, nullable=False)
    createdIn: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    updatedBy: Mapped[int | None] = mapped_column(Integer)
    updatedIn: Mapped[datetime | None] = mapped_column(DateTime)


class Team(Base):
    __tablename__ = "Teams"

    teamID: Mapped[int] = mapped_column(Integer, primary_key=True)
    baseRealCompetitionID: Mapped[int] = mapped_column(Integer, nullable=False)
    extraRealCompetitionID: Mapped[int | None] = mapped_column(Integer)
    matchDayMapKey: Mapped[str | None] = mapped_column(String(20))
    leagueID: Mapped[int] = mapped_column(Integer, nullable=False)
    divisionID: Mapped[int] = mapped_column(Integer, ForeignKey("Divisions.divisionID"), nullable=False)
    commissionerID: Mapped[int] = mapped_column(Integer, nullable=False)
    userID: Mapped[int | None] = mapped_column(Integer)
    prevLeagueID: Mapped[int | None] = mapped_column(Integer)
    nextLeagueID: Mapped[int | None] = mapped_column(Integer)
    prevDivisionID: Mapped[int | None] = mapped_column(Integer)
    nextDivisionID: Mapped[int | None] = mapped_column(Integer)
    prevTeamID: Mapped[int | None] = mapped_column(Integer)
    nextTeamID: Mapped[int | None] = mapped_column(Integer)
    season: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    seasonNum: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    leagueMatches: Mapped[int] = mapped_column(TinyInteger, default=0)
    divisionMatches: Mapped[int] = mapped_column(TinyInteger, default=0)
    draftOrder: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    randomOrder: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    waiversOrder: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    teamName: Mapped[str] = mapped_column(String(128), nullable=False)
    teamAvatar: Mapped[str | None] = mapped_column(String(128))
    teamMembers: Mapped[str] = mapped_column(Text, nullable=False)
    draftMembers: Mapped[str] = mapped_column(Text, nullable=False)
    membersRanking: Mapped[str] = mapped_column(Text, nullable=False)
    membersWaivers: Mapped[str] = mapped_column(Text, nullable=False)
    membersWishList: Mapped[str] = mapped_column(Text, nullable=False)
    franchiseWishList: Mapped[str] = mapped_column(Text, nullable=False)
    fantasyPoints: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    teamRanking: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    locked: Mapped[bool] = mapped_column(TinyInteger, nullable=False)
    isCommissioner: Mapped[bool] = mapped_column(TinyInteger, nullable=False)
    cntEPLTeam: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    cntPlayer: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    cntGoalkeeper: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    cntDefender: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    cntMidfielder: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    cntStriker: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    cntAdd: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    cntDrop: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    cntWaiver: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    notes: Mapped[str | None] = mapped_column(Text)
    place: Mapped[int | None] = mapped_column(SmallInteger)
    points: Mapped[int | None] = mapped_column(SmallInteger)
    statusC1: Mapped[int] = mapped_column(TinyInteger, default=0)
    statusC2: Mapped[int] = mapped_column(TinyInteger, default=0)
    statusC3: Mapped[int] = mapped_column(TinyInteger, default=0)
    seedingC1: Mapped[int] = mapped_column(TinyInteger, default=0)
    seedingC2: Mapped[int] = mapped_column(TinyInteger, default=0)
    seedingC3: Mapped[int] = mapped_column(TinyInteger, default=0)
    createdBy: Mapped[int] = mapped_column(Integer, nullable=False)
    createdIn: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    updatedBy: Mapped[int | None] = mapped_column(Integer)
    updatedIn: Mapped[datetime | None] = mapped_column(DateTime)


class MatchDaysMap(Base):
    __tablename__ = "MatchDaysMap"

    matchDayMapID: Mapped[int] = mapped_column(Integer, primary_key=True)
    baseRealCompetitionID: Mapped[int | None] = mapped_column(Integer)
    extraRealCompetitionID: Mapped[int | None] = mapped_column(Integer)
    competitionType: Mapped[int] = mapped_column(TinyInteger, nullable=False)
    minNumTeams: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    maxNumTeams: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    totalMatchDays: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    rounds: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    firstRealCompetitionMatchDay: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    firstRealCompetitionMatchDaySort: Mapped[int | None] = mapped_column(SmallInteger)
    matchDay: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    realCompetitionID: Mapped[int | None] = mapped_column(Integer)
    realCompetitionSYMID: Mapped[str] = mapped_column(String(20), nullable=False)
    realCompetitionSeasonId: Mapped[str] = mapped_column(String(20), nullable=False)
    realCompetitionMatchDay: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    realCompetitionMatchDaySort: Mapped[int | None] = mapped_column(SmallInteger)
    createdBy: Mapped[int] = mapped_column(Integer, nullable=False)
    createdIn: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    updatedBy: Mapped[int | None] = mapped_column(Integer)
    updatedIn: Mapped[datetime | None] = mapped_column(DateTime)


class MatchDaysStatus(Base):
    __tablename__ = "MatchDaysStatus"

    matchDayStatusID: Mapped[int] = mapped_column(Integer, primary_key=True)
    baseRealCompetitionID: Mapped[int | None] = mapped_column(Integer)
    extraRealCompetitionID: Mapped[int | None] = mapped_column(Integer)
    matchDayMapKey: Mapped[str | None] = mapped_column(String(20))
    realCompetitionID: Mapped[int | None] = mapped_column(Integer)
    realCompetitionSYMID: Mapped[str] = mapped_column(String(20), nullable=False)
    realCompetitionSeasonId: Mapped[str] = mapped_column(String(20), nullable=False)
    realCompetitionMatchDay: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    realCompetitionMatchDaySort: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    prevActiveMatchDayStatusID: Mapped[int | None] = mapped_column(Integer)
    prevActiveRealCompetitionID: Mapped[int | None] = mapped_column(Integer)
    prevActiveRealCompetitionSYMID: Mapped[str | None] = mapped_column(String(20))
    prevActiveRealCompetitionSeasonId: Mapped[str | None] = mapped_column(String(20))
    prevActiveRealCompetitionMatchDay: Mapped[int | None] = mapped_column(Integer)
    nextActiveMatchDayStatusID: Mapped[int | None] = mapped_column(Integer)
    nextActiveRealCompetitionID: Mapped[int | None] = mapped_column(Integer)
    nextActiveRealCompetitionSYMID: Mapped[str | None] = mapped_column(String(20))
    nextActiveRealCompetitionSeasonId: Mapped[str | None] = mapped_column(String(20))
    nextActiveRealCompetitionMatchDay: Mapped[int | None] = mapped_column(Integer)
    scriptsStatus: Mapped[str | None] = mapped_column(String(20))
    active: Mapped[bool] = mapped_column(TinyInteger, nullable=False)
    locked: Mapped[bool] = mapped_column(TinyInteger, default=0)
    overlapped: Mapped[bool] = mapped_column(TinyInteger, default=0)
    minAllowedRealMatchDate: Mapped[datetime | None] = mapped_column(DateTime)
    maxAllowedRealMatchDate: Mapped[datetime | None] = mapped_column(DateTime)
    minRealMatchDate: Mapped[datetime | None] = mapped_column(DateTime)
    maxRealMatchDate: Mapped[datetime | None] = mapped_column(DateTime)
    startWaivers: Mapped[datetime | None] = mapped_column(DateTime)
    finishWaivers: Mapped[datetime | None] = mapped_column(DateTime)
    startWaiversSettle: Mapped[datetime | None] = mapped_column(DateTime)
    finishWaiversSettle: Mapped[datetime | None] = mapped_column(DateTime)
    startOpenWaivers: Mapped[datetime | None] = mapped_column(DateTime)
    finishOpenWaivers: Mapped[datetime | None] = mapped_column(DateTime)
    startOpenWaiversSettle: Mapped[datetime | None] = mapped_column(DateTime)
    finishOpenWaiversSettle: Mapped[datetime | None] = mapped_column(DateTime)
    startPreMatch: Mapped[datetime | None] = mapped_column(DateTime)
    finishPreMatch: Mapped[datetime | None] = mapped_column(DateTime)
    startMatch: Mapped[datetime | None] = mapped_column(DateTime)
    finishMatch: Mapped[datetime | None] = mapped_column(DateTime)
    startPostMatch: Mapped[datetime | None] = mapped_column(DateTime)
    finishPostMatch: Mapped[datetime | None] = mapped_column(DateTime)
    startMatchDay: Mapped[datetime | None] = mapped_column(DateTime)
    finishMatchDay: Mapped[datetime | None] = mapped_column(DateTime)
    finishBaseMatchDay: Mapped[datetime | None] = mapped_column(DateTime)
