@base-url = https://eff-api-150703383580.us-central1.run.app
@user-agent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36
@user-id = 9
@new-user-email = testuser@example.com
@new-user-pass = TestPassword123


### 01. Sign up (Create new user)

POST {{base-url}}/api/v1/users
Content-Type: application/json
User-Agent: {{user-agent}}

{
  "userEmail": "{{new-user-email}}",
  "userPassword": "{{new-user-pass}}",
  "userName": "TestUser",
  "firstName": "Test",
  "lastName": "User",
  "birthday": "2000-01-01",
  "country": "US",
  "state": "US-TX",
  "city": "Austin",
  "phoneNumber": "5551234567",
  "timeZone": "1",
  "favoriteTeam": "Arsenal"
}


### 02. Update user profile - User {{user-id}}

PATCH {{base-url}}/api/v1/users/{{user-id}}
Content-Type: application/json
User-Agent: {{user-agent}}

{
  "firstName": "Nigel",
  "lastName": "Bowman",
  "birthday": "1957-06-19",
  "country": "US",
  "state": "US-TX",
  "city": "Austin",
  "phoneNumber": "5126338928",
  "timeZone": "1",
  "favoriteTeam": "Bristol City"
}
