@base-url = https://eff-api-150703383580.us-central1.run.app
@user-name = nigel@bowmantx.com
@user-pass = PASSWORD_9
@new-user-email = curltest@example.com
@new-user-pass = TestPass123


### SignIn (Token)
# @name signin

POST {{base-url}}/api/auth/signin
Content-Type: application/json

{
  "userEmail": "{{user-name}}",
  "userPassword": "{{user-pass}}"
}


### Extract token
@access-token = {{signin.response.body.token}}


### REST SignIn (Test)

POST {{base-url}}/api/auth/signin
Content-Type: application/json

{
  "userEmail": "{{user-name}}",
  "userPassword": "{{user-pass}}"
}


### REST SignUp

POST {{base-url}}/api/auth/signup
Content-Type: application/json

{
  "userEmail": "{{new-user-email}}",
  "userPassword": "{{new-user-pass}}",
  "userName": "TestUser",
  "firstName": "Test",
  "lastName": "User",
  "birthday": "2000-01-01",
  "country": "US",
  "state": "US-TX",
  "city": "Austin",
  "phoneNumber": "5551234567",
  "timeZone": "1",
  "favoriteTeam": "Arsenal"
}


### REST SignOut

POST {{base-url}}/api/auth/signout
Content-Type: application/json
Authorization: Bearer {{access-token}}


### REST Update User Profile
# Update user with ID 9

PATCH {{base-url}}/api/auth/users/9
Content-Type: application/json
Authorization: Bearer {{access-token}}

{
  "firstName": "Nigel",
  "lastName": "Bowman",
  "birthday": "1957-06-19",
  "country": "US",
  "state": "US-TX",
  "city": "Austin",
  "phoneNumber": "5126338928",
  "timeZone": "1",
  "favoriteTeam": "Bristol City"
}
