@base-url = https://eff-api-150703383580.us-central1.run.app
@user-name = nigel@bowmantx.com
@user-pass = PASSWORD_9
@division-id = 130
@real-competition-id = 21
@match-id = 1


### SignIn (Token)
# @name signin

POST {{base-url}}/api/auth/signin
Content-Type: application/json

{
  "userEmail": "{{user-name}}",
  "userPassword": "{{user-pass}}"
}


### Extract token
@access-token = {{signin.response.body.token}}


### Matches ReadList

POST {{base-url}}/api/matches/readlist
Content-Type: application/json
Authorization: Bearer {{access-token}}

{
  "divisionID": {{division-id}}
}


### Match Teams ReadList

POST {{base-url}}/api/matchteams/readlist
Content-Type: application/json
Authorization: Bearer {{access-token}}

{
  "matchID": {{match-id}}
}


### Real Matches ReadList

POST {{base-url}}/api/realmatches/readlist
Content-Type: application/json
Authorization: Bearer {{access-token}}

{
  "realCompetitionID": {{real-competition-id}},
  "realCompetitionSeasonID": 2025
}


### Real Match Teams ReadList

POST {{base-url}}/api/realmatchteams/readlist
Content-Type: application/json
Authorization: Bearer {{access-token}}

{
  "realMatchID": 1
}
